### ISSUE TITLE
Some issues in version 11 beta

### ISSUE THREAD

**Issue by jjdiaz** [PixelExperience-Devices/device_xiaomi_ginkgo#11]
Hi,

I've found some issues after installing PixelExperience_ginkgo-11.0-20210123-0351-BETA-OFFICIAL.zip in my Redmi NOte 8

* The camera does not run fine. It hangs after take a picture or when changing to the front camera.
* The facial recognition does not appear.
* Unblock the phone by finger sensor does not work.
* Pixel camera does not work. In a MI5 runs ok.
* Screen lack when using animated screen background.

Thanks for your excelent job
Regards.
Joaquin

**Comment by AndrielFR** [comment]
About the camera: I will test the MiUI camera, if it is ok, I will use it.
About facial recognition: it will be released next month.
About digital unlocking: send me logs on Telegram, as it is working normally here.
About the Pixel camera: I will check, but it was working here, send me the apk and log on Telegram.
About the animated background: I deactivated, here it also causes a lot of lag.
Wait for these bugs fixed in next month's build.
